name: Deploy TU Result Checker

on:
  push:
    branches:
      - main # trigger only on main branch updates

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd /root/tu-result-checker
            git fetch --all
            git reset --hard origin/main
            source myenv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart tu-result-checker
